name: Publish Docker Image

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
#    runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest
#    strategy:
#      matrix:
##        os: [ ubuntu-latest, windows-latest ]
#        os: [ ubuntu-latest ]
#        incloud:
#          - architecture: amd64
#          - architecture: arm64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: zhangyiming748/whisperandtrans

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}